# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6a4a1a42f85ac0851e3f983f34118c89d6a83d82177a7b5446625a2be85decad1c3a6d95f47115c27afe2ae15f65d0fbddbb52ea624fbb95cea625cc40408ea

test:
  secret_key_base: e22495873bfcc681610f41a0fb80e616bc26e75966c5d0106ab7e4cf6ae5a81e68457503d2ce41ed85906ef5b393c4d030569a485649c996360121efe59589cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
